name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: ["ghc-9.4"]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.6"]
        ghc:
          - "9.4"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/ghc-head'

    - name: Install gmp and tinfo
      run: |
        sudo -- sh -c "apt-get update"
        sudo -- sh -c "apt-get -y install libgmp-dev libtinfo-dev"
    - name: Configure ghcup
      run: |
        ghcup config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml

    - uses: haskell/actions/setup@main
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Prepare environment
      run: echo "$HOME/.ghcup/bin" >> $GITHUB_PATH

    - name: Freeze
      run: |
        cabal freeze
 
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    - name: Test
      run: cabal test all
