name: hlint

on:
  pull_request:
  push:

jobs:
  build:
    name: hlint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.8"]
        ghc:
          # GHC head is broken on GitHub Actions: https://github.com/haskell/actions/issues/137#issuecomment-1362677728
          # - "head"
          - "9.4"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install tinfo5
      run: |
        sudo -- sh -c "apt-get update"
        sudo -- sh -c "apt-get -y install libtinfo5"

    - uses: haskell/actions/setup@main
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Freeze
      run: |
        cabal freeze

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Set up HLint
      run: cabal install hlint

    - uses: rwe/actions-hlint-run@v2
      name: hlint
      with:
        path: '[ "haddock-library/", "haddock-api/", "haddock-test/", "hoogle-test/", "html-test/", "hypsrc-test/", "latex-test/" ]'
        fail-on: suggestion
        hlint-bin: ${{ steps.setup-haskell-cabal.outputs.cabal-store}}/../bin/hlint
